// Code generated by go generate; DO NOT EDIT.
package m

type Items interface {
	// Used in all types of construction and ammunition.
	Copper() int
	// Used in liquid transportation and electrical structures.
	Lead() int
	// Used in liquid distribution/storage structures.
	Metaglass() int
	// Used in electrical components and turret ammunition.
	Graphite() int
	// Used for production of other refined materials.
	Sand() int
	// Used for fuel and refined material production.
	Coal() int
	// Used in liquid transportation structures, drills and factories.
	Titanium() int
	// Used in durable structures and as nuclear fuel.
	Thorium() int
	// Used in Melters and Pulverizers for refining into other materials.
	Scrap() int
	// Used in solar panels, complex electronics and homing turret ammunition.
	Silicon() int
	// Used in advanced units, insulation and fragmentation ammunition.
	Plastanium() int
	// Used in advanced electronics and self-repairing structures.
	PhaseFabric() int
	// Used in advanced weaponry and reactive defense structures.
	SurgeAlloy() int
	// Used for conversion into oil, explosives and fuel.
	SporePod() int
	// Used in bombs and explosive ammunition.
	BlastCompound() int
	// Used in incendiary weapons and combustion-fueled generators.
	Pyratite() int
	// Used in many types of construction and ammunition on Erekir.
	Beryllium() int
	// Used in drills, armor and ammunition. Required in the construction of more advanced structures.
	Tungsten() int
	// Used as a heat conductor and insulator for power.
	Oxide() int
	// Used in advanced structures, heavier units, and ammunition.
	Carbide() int
}

type Liquids interface {
	// Used for cooling machines and waste processing.
	Water() float64
	// Refined in separators into constituent metals. Consumed in liquid turrets as ammunition.
	Slag() float64
	// Used in advanced material production and as incendiary ammunition.
	Oil() float64
	// Used as coolant in reactors, turrets and factories.
	Cryofluid() float64
	// Used in chemical reactions for power generation and material synthesis.
	Arkycite() float64
	// Used as fuel and an oxidizing agent in material production. Moderately explosive.
	Ozone() float64
	// Used in resource extraction, unit production and structure repair. Flammable.
	Hydrogen() float64
	// Used for ammunition, construction of advanced units, and various reactions in advanced blocks. Highly flammable.
	Cyanogen() float64
	// Used in resource extraction, gas creation and unit production. Inert.
	Nitrogen() float64
	// A dangerous biological byproduct of the Neoplasia reactor. Quickly spreads to any adjacent water-containing block it touches, damaging them in the process. Viscous.
	Neoplasm() float64
}
