// Code generated by go generate; DO NOT EDIT.
package impl

import "github.com/Vilsol/go-mlog/transpiler"

func init() {
	// Items
	transpiler.RegisterFuncTranslation("Copper", createSensorFuncTranslation("@copper"))
	transpiler.RegisterFuncTranslation("Lead", createSensorFuncTranslation("@lead"))
	transpiler.RegisterFuncTranslation("Metaglass", createSensorFuncTranslation("@metaglass"))
	transpiler.RegisterFuncTranslation("Graphite", createSensorFuncTranslation("@graphite"))
	transpiler.RegisterFuncTranslation("Sand", createSensorFuncTranslation("@sand"))
	transpiler.RegisterFuncTranslation("Coal", createSensorFuncTranslation("@coal"))
	transpiler.RegisterFuncTranslation("Titanium", createSensorFuncTranslation("@titanium"))
	transpiler.RegisterFuncTranslation("Thorium", createSensorFuncTranslation("@thorium"))
	transpiler.RegisterFuncTranslation("Scrap", createSensorFuncTranslation("@scrap"))
	transpiler.RegisterFuncTranslation("Silicon", createSensorFuncTranslation("@silicon"))
	transpiler.RegisterFuncTranslation("Plastanium", createSensorFuncTranslation("@plastanium"))
	transpiler.RegisterFuncTranslation("PhaseFabric", createSensorFuncTranslation("@phase-fabric"))
	transpiler.RegisterFuncTranslation("SurgeAlloy", createSensorFuncTranslation("@surge-alloy"))
	transpiler.RegisterFuncTranslation("SporePod", createSensorFuncTranslation("@spore-pod"))
	transpiler.RegisterFuncTranslation("BlastCompound", createSensorFuncTranslation("@blast-compound"))
	transpiler.RegisterFuncTranslation("Pyratite", createSensorFuncTranslation("@pyratite"))
	transpiler.RegisterFuncTranslation("Beryllium", createSensorFuncTranslation("@beryllium"))
	transpiler.RegisterFuncTranslation("Tungsten", createSensorFuncTranslation("@tungsten"))
	transpiler.RegisterFuncTranslation("Oxide", createSensorFuncTranslation("@oxide"))
	transpiler.RegisterFuncTranslation("Carbide", createSensorFuncTranslation("@carbide"))

	// Liquids
	transpiler.RegisterFuncTranslation("Water", createSensorFuncTranslation("@water"))
	transpiler.RegisterFuncTranslation("Slag", createSensorFuncTranslation("@slag"))
	transpiler.RegisterFuncTranslation("Oil", createSensorFuncTranslation("@oil"))
	transpiler.RegisterFuncTranslation("Cryofluid", createSensorFuncTranslation("@cryofluid"))
	transpiler.RegisterFuncTranslation("Arkycite", createSensorFuncTranslation("@arkycite"))
	transpiler.RegisterFuncTranslation("Ozone", createSensorFuncTranslation("@ozone"))
	transpiler.RegisterFuncTranslation("Hydrogen", createSensorFuncTranslation("@hydrogen"))
	transpiler.RegisterFuncTranslation("Cyanogen", createSensorFuncTranslation("@cyanogen"))
	transpiler.RegisterFuncTranslation("Nitrogen", createSensorFuncTranslation("@nitrogen"))
	transpiler.RegisterFuncTranslation("Neoplasm", createSensorFuncTranslation("@neoplasm"))
}
